# 复数运算

## 复数可以通过complex(real, imag)函数来指定，或者通过浮点数再加上后缀来指定

In [1]:
a = complex(2, 4)
b = 3 - 5j

In [2]:
a

(2+4j)

In [3]:
b

(3-5j)

共轭

In [4]:
a.conjugate()

(2-4j)

虚部

In [5]:
a.imag

4.0

实部

In [6]:
b.real

3.0

In [7]:
a + b

(5-1j)

In [8]:
a * b

(26+2j)

In [9]:
a / b

(-0.4117647058823529+0.6470588235294118j)

In [10]:
abs(a)

4.47213595499958

## 执行复数的函数操作：正弦、余弦、平方根，可以使用cmath模块

In [11]:
import cmath
cmath.sin(a)

(24.83130584894638-11.356612711218174j)

In [12]:
cmath.cos(a)

(-11.36423470640106-24.814651485634187j)

In [13]:
cmath.exp(a)

(-4.829809383269385-5.5920560936409816j)

## python中大部分和数学相关的模块都可用于复数。如numpy模块

In [14]:
import numpy as np

In [15]:
a = np.array([2 + 3j, 4 + 5j, 6 - 7j, 8 + 9j])
a

array([ 2.+3.j,  4.+5.j,  6.-7.j,  8.+9.j])

In [16]:
a + 2

array([  4.+3.j,   6.+5.j,   8.-7.j,  10.+9.j])

In [17]:
np.abs(a)

array([  3.60555128,   6.40312424,   9.21954446,  12.04159458])

## python中标准数学函数默认情况不会产生复数值。

In [18]:
import math
math.sqrt(-1)

ValueError: math domain error

希望产生复数则必须使用cmath模块，或者在可以感知复数的库中声明对复数的使用

In [19]:
import cmath
cmath.sqrt(-1)

1j